services: 
  mysql:
    image: mysql:8.4
    restart: always
    container_name: mysql
    environment:
      - MYSQL_DATABASE=db_agenda
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - '3306:3306'
    networks:
      - my-network
networks:
  my-network:
    driver: bridge